// ============================================================
// UrbanPulse — Simulated Data Layer
// Uses structured, realistic data to demonstrate the system.
// In production, this data comes from the Edge AI pipeline.
// ============================================================

import { RoadEvent, Bus, PipelineStage, DashboardStats } from './types';

export const simulatedBuses: Bus[] = [
  {
    id: 'BUS-KA01-001',
    routeNumber: '201-C',
    routeName: 'Koramangala → Indiranagar',
    status: 'active',
    currentLocation: { lat: 12.9352, lng: 77.6245 },
    lastPing: new Date(Date.now() - 30000).toISOString(),
    eventsDetected: 14,
    speed: 28,
    cameraStatus: 'online',
  },
  {
    id: 'BUS-KA01-002',
    routeNumber: '500-D',
    routeName: 'Majestic → Whitefield',
    status: 'active',
    currentLocation: { lat: 12.9864, lng: 77.7120 },
    lastPing: new Date(Date.now() - 15000).toISOString(),
    eventsDetected: 22,
    speed: 35,
    cameraStatus: 'online',
  },
  {
    id: 'BUS-KA01-003',
    routeNumber: '335-A',
    routeName: 'Yelahanka → Electronic City',
    status: 'active',
    currentLocation: { lat: 13.0569, lng: 77.5743 },
    lastPing: new Date(Date.now() - 45000).toISOString(),
    eventsDetected: 8,
    speed: 22,
    cameraStatus: 'online',
  },
  {
    id: 'BUS-KA01-004',
    routeNumber: '201-F',
    routeName: 'BTM Layout → Silk Board',
    status: 'idle',
    currentLocation: { lat: 12.9165, lng: 77.6101 },
    lastPing: new Date(Date.now() - 300000).toISOString(),
    eventsDetected: 0,
    speed: 0,
    cameraStatus: 'offline',
  },
  {
    id: 'BUS-KA01-005',
    routeNumber: 'G9',
    routeName: 'Shivajinagar → RR Nagar',
    status: 'active',
    currentLocation: { lat: 12.9719, lng: 77.5249 },
    lastPing: new Date(Date.now() - 20000).toISOString(),
    eventsDetected: 18,
    speed: 31,
    cameraStatus: 'online',
  },
  {
    id: 'BUS-KA01-006',
    routeNumber: 'MF-01',
    routeName: 'Metro Feeder — Hebbal',
    status: 'maintenance',
    currentLocation: { lat: 13.0358, lng: 77.5970 },
    lastPing: new Date(Date.now() - 3600000).toISOString(),
    eventsDetected: 5,
    speed: 0,
    cameraStatus: 'offline',
  },
];

// Simulated road events demonstrating multi-pass verification
export const simulatedEvents: RoadEvent[] = [
  {
    id: 'EVT-001',
    type: 'pothole',
    location: { lat: 12.9355, lng: 77.6240 },
    firstDetected: new Date(Date.now() - 7200000).toISOString(),
    lastDetected: new Date(Date.now() - 600000).toISOString(),
    observations: [
      {
        id: 'OBS-001-A',
        busId: 'BUS-KA01-001',
        timestamp: new Date(Date.now() - 7200000).toISOString(),
        confidence: 0.82,
        location: { lat: 12.9355, lng: 77.6240 },
      },
      {
        id: 'OBS-001-B',
        busId: 'BUS-KA01-002',
        timestamp: new Date(Date.now() - 3600000).toISOString(),
        confidence: 0.87,
        location: { lat: 12.9356, lng: 77.6241 },
      },
      {
        id: 'OBS-001-C',
        busId: 'BUS-KA01-001',
        timestamp: new Date(Date.now() - 600000).toISOString(),
        confidence: 0.91,
        location: { lat: 12.9355, lng: 77.6240 },
      },
    ],
    status: 'verified',
    priority: 'high',
    severity: 7,
    description: 'Large pothole (~40cm diameter) on main carriageway, right lane',
    address: '80 Feet Road, Koramangala 4th Block',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'EVT-002',
    type: 'road_crack',
    location: { lat: 12.9860, lng: 77.7115 },
    firstDetected: new Date(Date.now() - 10800000).toISOString(),
    lastDetected: new Date(Date.now() - 1800000).toISOString(),
    observations: [
      {
        id: 'OBS-002-A',
        busId: 'BUS-KA01-002',
        timestamp: new Date(Date.now() - 10800000).toISOString(),
        confidence: 0.74,
        location: { lat: 12.9860, lng: 77.7115 },
      },
      {
        id: 'OBS-002-B',
        busId: 'BUS-KA01-002',
        timestamp: new Date(Date.now() - 1800000).toISOString(),
        confidence: 0.79,
        location: { lat: 12.9861, lng: 77.7116 },
      },
    ],
    status: 'pending_verify',
    priority: 'medium',
    severity: 5,
    description: 'Network cracking pattern on road surface, ~3m length',
    address: 'ITPL Main Road, Whitefield',
    createdAt: new Date(Date.now() - 10800000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'EVT-003',
    type: 'waterlogging',
    location: { lat: 12.9545, lng: 77.6970 },
    firstDetected: new Date(Date.now() - 5400000).toISOString(),
    lastDetected: new Date(Date.now() - 900000).toISOString(),
    observations: [
      {
        id: 'OBS-003-A',
        busId: 'BUS-KA01-002',
        timestamp: new Date(Date.now() - 5400000).toISOString(),
        confidence: 0.88,
        location: { lat: 12.9545, lng: 77.6970 },
      },
      {
        id: 'OBS-003-B',
        busId: 'BUS-KA01-005',
        timestamp: new Date(Date.now() - 2700000).toISOString(),
        confidence: 0.92,
        location: { lat: 12.9546, lng: 77.6971 },
      },
      {
        id: 'OBS-003-C',
        busId: 'BUS-KA01-002',
        timestamp: new Date(Date.now() - 900000).toISOString(),
        confidence: 0.95,
        location: { lat: 12.9545, lng: 77.6970 },
      },
      {
        id: 'OBS-003-D',
        busId: 'BUS-KA01-005',
        timestamp: new Date(Date.now() - 300000).toISOString(),
        confidence: 0.93,
        location: { lat: 12.9545, lng: 77.6970 },
      },
    ],
    status: 'actioned',
    priority: 'critical',
    severity: 9,
    description: 'Severe waterlogging at intersection, depth ~30cm, blocking right turn',
    address: 'Marathahalli Bridge Junction',
    createdAt: new Date(Date.now() - 5400000).toISOString(),
    updatedAt: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: 'EVT-004',
    type: 'pothole',
    location: { lat: 13.0560, lng: 77.5738 },
    firstDetected: new Date(Date.now() - 1800000).toISOString(),
    lastDetected: new Date(Date.now() - 1800000).toISOString(),
    observations: [
      {
        id: 'OBS-004-A',
        busId: 'BUS-KA01-003',
        timestamp: new Date(Date.now() - 1800000).toISOString(),
        confidence: 0.68,
        location: { lat: 13.0560, lng: 77.5738 },
      },
    ],
    status: 'unverified',
    priority: 'low',
    severity: 3,
    description: 'Possible pothole detected, single observation — needs re-confirmation',
    address: 'Yelahanka New Town Road',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'EVT-005',
    type: 'traffic_congestion',
    location: { lat: 12.9719, lng: 77.5250 },
    firstDetected: new Date(Date.now() - 900000).toISOString(),
    lastDetected: new Date(Date.now() - 120000).toISOString(),
    observations: [
      {
        id: 'OBS-005-A',
        busId: 'BUS-KA01-005',
        timestamp: new Date(Date.now() - 900000).toISOString(),
        confidence: 0.91,
        location: { lat: 12.9719, lng: 77.5250 },
      },
      {
        id: 'OBS-005-B',
        busId: 'BUS-KA01-005',
        timestamp: new Date(Date.now() - 450000).toISOString(),
        confidence: 0.94,
        location: { lat: 12.9720, lng: 77.5251 },
      },
      {
        id: 'OBS-005-C',
        busId: 'BUS-KA01-005',
        timestamp: new Date(Date.now() - 120000).toISOString(),
        confidence: 0.96,
        location: { lat: 12.9719, lng: 77.5250 },
      },
    ],
    status: 'verified',
    priority: 'medium',
    severity: 6,
    description: 'Persistent congestion — average speed < 10 km/h for 15+ minutes',
    address: 'Mysore Road Junction',
    createdAt: new Date(Date.now() - 900000).toISOString(),
    updatedAt: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: 'EVT-006',
    type: 'road_sign_damage',
    location: { lat: 12.9450, lng: 77.6100 },
    firstDetected: new Date(Date.now() - 4800000).toISOString(),
    lastDetected: new Date(Date.now() - 2400000).toISOString(),
    observations: [
      {
        id: 'OBS-006-A',
        busId: 'BUS-KA01-001',
        timestamp: new Date(Date.now() - 4800000).toISOString(),
        confidence: 0.76,
        location: { lat: 12.9450, lng: 77.6100 },
      },
      {
        id: 'OBS-006-B',
        busId: 'BUS-KA01-004',
        timestamp: new Date(Date.now() - 2400000).toISOString(),
        confidence: 0.81,
        location: { lat: 12.9451, lng: 77.6101 },
      },
    ],
    status: 'pending_verify',
    priority: 'low',
    severity: 3,
    description: 'Speed limit sign damaged/tilted, partially obscured',
    address: 'HSR Layout Sector 2',
    createdAt: new Date(Date.now() - 4800000).toISOString(),
    updatedAt: new Date(Date.now() - 2400000).toISOString(),
  },
  {
    id: 'EVT-007',
    type: 'pothole',
    location: { lat: 12.9600, lng: 77.6500 },
    firstDetected: new Date(Date.now() - 14400000).toISOString(),
    lastDetected: new Date(Date.now() - 7200000).toISOString(),
    observations: [
      {
        id: 'OBS-007-A',
        busId: 'BUS-KA01-001',
        timestamp: new Date(Date.now() - 14400000).toISOString(),
        confidence: 0.85,
        location: { lat: 12.9600, lng: 77.6500 },
      },
      {
        id: 'OBS-007-B',
        busId: 'BUS-KA01-002',
        timestamp: new Date(Date.now() - 10800000).toISOString(),
        confidence: 0.88,
        location: { lat: 12.9601, lng: 77.6501 },
      },
      {
        id: 'OBS-007-C',
        busId: 'BUS-KA01-005',
        timestamp: new Date(Date.now() - 7200000).toISOString(),
        confidence: 0.90,
        location: { lat: 12.9600, lng: 77.6500 },
      },
    ],
    status: 'actioned',
    priority: 'high',
    severity: 8,
    description: 'Multiple potholes in cluster, ~60cm total width, hazard for two-wheelers',
    address: 'Sarjapur Road, Near Bellandur',
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'EVT-008',
    type: 'zebra_crossing_deficiency',
    location: { lat: 12.9780, lng: 77.6400 },
    firstDetected: new Date(Date.now() - 6000000).toISOString(),
    lastDetected: new Date(Date.now() - 3000000).toISOString(),
    observations: [
      {
        id: 'OBS-008-A',
        busId: 'BUS-KA01-001',
        timestamp: new Date(Date.now() - 6000000).toISOString(),
        confidence: 0.72,
        location: { lat: 12.9780, lng: 77.6400 },
      },
      {
        id: 'OBS-008-B',
        busId: 'BUS-KA01-002',
        timestamp: new Date(Date.now() - 3000000).toISOString(),
        confidence: 0.75,
        location: { lat: 12.9781, lng: 77.6401 },
      },
    ],
    status: 'pending_verify',
    priority: 'medium',
    severity: 5,
    description: 'Zebra crossing faded/missing near school zone',
    address: 'CMR Road, Indiranagar',
    createdAt: new Date(Date.now() - 6000000).toISOString(),
    updatedAt: new Date(Date.now() - 3000000).toISOString(),
  },
];

export const pipelineStages: PipelineStage[] = [
  {
    id: 'stage-1',
    name: 'Camera + GPS Input',
    description: 'Frame capture + GPS coordinate + timestamp',
    status: 'active',
    throughput: 30,
    lastProcessed: new Date(Date.now() - 1000).toISOString(),
  },
  {
    id: 'stage-2',
    name: 'Edge AI Detection',
    description: 'YOLO inference — pothole, crack, vehicle, sign detection',
    status: 'processing',
    throughput: 25,
    lastProcessed: new Date(Date.now() - 2000).toISOString(),
  },
  {
    id: 'stage-3',
    name: 'Confidence Filter',
    description: 'Threshold check — discard low-confidence detections',
    status: 'active',
    throughput: 22,
    lastProcessed: new Date(Date.now() - 3000).toISOString(),
  },
  {
    id: 'stage-4',
    name: 'Spatial Matching',
    description: 'Match new detections to existing events within radius',
    status: 'active',
    throughput: 20,
    lastProcessed: new Date(Date.now() - 4000).toISOString(),
  },
  {
    id: 'stage-5',
    name: 'Temporal Validation',
    description: 'Multi-pass verification — time-window confirmation',
    status: 'active',
    throughput: 18,
    lastProcessed: new Date(Date.now() - 5000).toISOString(),
  },
  {
    id: 'stage-6',
    name: 'Priority Scoring',
    description: 'Severity × frequency × recency scoring',
    status: 'active',
    throughput: 18,
    lastProcessed: new Date(Date.now() - 5500).toISOString(),
  },
  {
    id: 'stage-7',
    name: 'Authority Queue',
    description: 'Verified events → maintenance dispatch',
    status: 'active',
    throughput: 15,
    lastProcessed: new Date(Date.now() - 6000).toISOString(),
  },
];

export const dashboardStats: DashboardStats = {
  totalEvents: simulatedEvents.length,
  verifiedEvents: simulatedEvents.filter(e => e.status === 'verified' || e.status === 'actioned').length,
  activeBuses: simulatedBuses.filter(b => b.status === 'active').length,
  criticalIssues: simulatedEvents.filter(e => e.priority === 'critical').length,
  eventsToday: 47,
  avgConfidence: 0.84,
  multiPassRate: 0.72,
};
